# Default configuration values
DEFAULT_SECRET_KEY = "dev-secret-key"
DEFAULT_DATABASE_URI = "sqlite:///app.db"
DEFAULT_JWT_EXPIRATION_MINUTES = 60
# Environment variable names
SECRET_KEY_ENV = "SECRET_KEY"
JWT_SECRET_KEY_ENV = "JWT_SECRET_KEY"
JWT_EXPIRATION_MINUTES_ENV = "JWT_EXPIRATION_MINUTES"
DATABASE_URI_ENV = "DATABASE_URI"

